#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#
# shellcheck source=config/sources/families/include/meson64_common.inc
source "${BASH_SOURCE%/*}/include/meson64_common.inc"
ASOUND_STATE="${ASOUND_STATE:-"asound.state.meson64"}"
CPUMIN=667000
CPUMAX=2100000
GOVERNOR=ondemand

family_tweaks() {
	:
}

uboot_custom_postprocess() {
	uboot_g12_postprocess $SRC/cache/sources/amlogic-boot-fip/odroid-c4 g12a
}
