# Amlogic S905X3 quad core 4GB RAM SoC eMMC GBE USB3 SPI
BOARD_NAME="AtriStation"
BOARD_VENDOR="leftymods"
BOARDFAMILY="meson-sm1"
BOARD_MAINTAINER="leftymods"
INTRODUCED="2025"
VENDOR="AtriOS"
VENDORURL="https://github.com/leftymods/CoreOS"
VENDORSUPPORT="https://github.com/leftymods/CoreOS"
VENDORDOCS="https://github.com/leftymods/CoreOS"
VENDORBUGS="https://github.com/leftymods/CoreOS"
MAINTAINERMAIL="leftymods@users.noreply.github.com"
INTRODUCED="2020"
BOOTCONFIG="odroid-c4_defconfig"
KERNEL_TARGET="current"
BOOT_FDT_FILE="amlogic/meson-sm1-x96-max-plus.dtb"
MODULES_BLACKLIST="simpledrm" # SimpleDRM conflicts with Panfrost
FULL_DESKTOP="yes"
SERIALCON="ttyAML0"
BOOT_LOGO="desktop"
